### ISSUE TITLE
[Doc] Converting back from SyncTask to Promise

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/SyncTasks#16]
This might seem a bit counter-intuitive, but I think there should be a supported mechanism for converting a SyncTask back to a regular promise (maybe a .toPromise()?). Or at least some documentation around how to do this yourself.

ReactXP returns SyncTask promises in its APIs for example, but doesn't tell the caller how to go back to a regular promise if that is what they want to do. This puts the caller in the awkward situation where they have to either go all-in on SyncTasks or just not use the API.

**Comment by boguscoder** [comment]
Smth along these lines?

    asEsPromise<T>(syncPromise: SyncTasks.Promise<T>): Promise<T> {
        return new Promise<T>((resolve, reject) => syncPromise.then(resolve, reject));
    }

**Comment by erictraut** [comment]
Any reason why we shouldn't just add this method to the SyncTasks.Promise class?

**Comment by deregtd** [comment]
Seems fair enough to me.

**Comment by deregtd** [comment]
Should be addressed with the avove PR!

**Comment by luisnaranjo733** [comment]
When can we expect version 0.3.3 to be shipped? The latest on npmjs.com is still 0.3.2.
