### ISSUE TITLE
[Publish] When will the next version of SyncTasks be published?

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/SyncTasks#20]
This [issue](https://github.com/Microsoft/SyncTasks/issues/16) got fixed and merged in, but there hasn't been a new version published to npmjs.com. I'm guessing it would be version 0.4 since it has a new feature but doesn't have any breaking changes (or 0.3.3 for simplicity).

Is there an ETA on when that might happen? I'm opening this issue for visibility because the previous one got closed.

**Comment by erictraut** [comment]
@deregtd, are you waiting on any other changes before publishing the next version? If not, can you bump the version and publish? Thx

**Comment by deregtd** [comment]
Oh sorry, I asked my team yesterday if someone could publish it, but everyone was AWOL.  I'll get something up shortly.

**Comment by deregtd** [comment]
0.3.3 published

**Comment by luisnaranjo733** [comment]
Thanks!
